### ISSUE TITLE
[META] Maintenance: Sentry improvements and bug fixes (WIP)

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1042]
There are some new features and improvements to our workflow that can be made to improve the quality of information gleaned from Sentry. Many of these items will require updating our version of the SDK (a small change, basically bumping the npm package version.)

- [x] Implement [release tracking](https://docs.sentry.io/workflow/releases/?platform=javascript), which will tell us the release in which an error is introduced, even down to the commit level in some instances
  - [x] We would need a [GitHub Action](https://blog.sentry.io/2019/12/17/using-github-actions-to-create-sentry-releases) that notifies Sentry whenever we tag a release.
- [x] Connect the Sentry [GitHub integration](https://sentry.io/integrations/github/) which allows connecting issues to errors within Sentry

In addition to the above, the following production bugs should be fixed (with standalone issues to be added here) **[work in progress]:**
-  [x] `NavigationDuplicated`: https://sentry.io/organizations/creative-commons/issues/1646462373/?project=1525413&query=is%3Aunresolved
- [x] `TypeError: tagName is undefined`: https://sentry.io/organizations/creative-commons/issues/1663506310/?project=1525413&query=is%3Aunresolved&sort=priority&statsPeriod=14d

**Comment by kgodey** [comment]
Reopening since not everything in the meta ticket is done.
