### ISSUE TITLE
[META] Internationalisation (i18n) Setup

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#487]
This should be about adding i18n support, not the translations themselves.
Even if we continue supporting only English initially, it's good to have support for i18n and do the translations later.

Sub-tasks:

- [x] Set up vue-i18n infrastructure: installing [vue-i18n package](https://kazupon.github.io/vue-i18n/) and setting up the internationalization infrastructure on both client and server renderers (See #941)
- [x] Create the translations JSON message object schema, research which [formatters](https://kazupon.github.io/vue-i18n/guide/formatting.html) will be required to render text and numbers. (See #942)
- [x] Allow users to change locale on the client (See #943)
- [x] Set up translation service infrastructure, as of this writing, with https://www.transifex.com/ (See #944)
- [ ] Set up locale detection on the server to load appropriate localized messages (See #945)

**Comment by sharmaaditya570191** [comment]
Can I take this up?

**Comment by brenoferreira** [comment]
This will be part of our Google Summer of Code project, so we aren't working on this at the moment. If you want to participate in the program, you're welcome to submit a project proposal

**Comment by Geqwe** [comment]
> This will be part of our Google Summer of Code project, so we aren't working on this at the moment. If you want to participate in the program, you're welcome to submit a project proposal

I'm interested in participating in GSoC and if I am selected, do this specific project. Except for applying in the proposal process what do you propose doing until then? (Read all guidelines in the ideas pages about accessibility,  vue-i18n, etc and I am experienced in Vue Js) Thanks in advance.

**Comment by akmadian** [comment]
@Geqwe Please see [CC's internship applicant guide](https://opensource.creativecommons.org/internships/applicant-guide/)
