### ISSUE TITLE
[META] Accessibility (a11y) Improvements

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#488]
Roadmap of tasks:

- [x] Run audit on accessibility with [Lighthouse](https://developers.google.com/web/tools/lighthouse), [Accessibility Insights](https://accessibilityinsights.io/) and [pa11y](https://pa11y.org) and compile reports on which issues are higher priority.

These tools will probably find issues with the following:
- [x] Aria labels (these will have to be internationalized) See #996 
- [x] tabIndex of components. See #997
- [x] evaluate improvements to have a more semantic markup #999
- [x] Check color contrast problems (Chrome DevTools has a good [tool](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#contrast) for this See #998
- [x] Component Issues:
    - [x] Modal: #1052
- [x] Bonus: evaluate if possible to add Lint tools to check for accessibility errors #1000

**Comment by kerryja** [comment]
Hello, I can tackle this!

**Comment by hemanth-hk** [comment]
Can I take this?

### Method :
I'll use pa11y to see accessibility issues and once I get the CSS selector I'll manually edit them

**Comment by brenoferreira** [comment]
This will be part of our Google Summer of Code project, so we aren't working on this at the moment. If you want to participate in the program, you're welcome to submit a project proposal

**Comment by hemanth-hk** [comment]
Okay

**Comment by brenoferreira** [comment]
This might be useful when work starts on this https://github.com/creativecommons/cccatalog-frontend/issues/599#issuecomment-587508463

**Comment by highflyer910** [comment]
May I work on this as an Outreachy applicant?

**Comment by akmadian** [comment]
Hey @highflyer910, since this issue is a part of our Outreachy/ GSoC project, you'll have to submit a project proposal as per the Outreachy/ GSoC process and get accepted to work on this

**Comment by highflyer910** [comment]
@akmadian , Did you mean I need to be an intern to work on this issue?

**Comment by akmadian** [comment]
@highflyer910 yes

**Comment by akmadian** [comment]
Came across this article, it may be of help: https://marcysutton.com/how-i-audit-a-website-for-accessibility

**Comment by highflyer910** [comment]
Thank you, but I already have experience in accessibility and that's why I wanted to work on this... So maybe you can guide where to start and which issues to lookout?

**Comment by akmadian** [comment]
@highflyer910 Experience with accessibility is definetely a plus, be sure to mention it in your project proposal! 

Please have a thorough read through [CC's Internship Applicant Guide](https://opensource.creativecommons.org/internships/applicant-guide/) and [CC's Code Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

**Comment by AyanChoudhary** [comment]
Reopening since more work needs to be done.

**Comment by zackkrida** [comment]
thanks @AyanChoudhary it auto-closed when i merged your last work!

**Comment by AyanChoudhary** [comment]
Reopening, apparently github closes the issue even if you tag it with partially fixes.

**Comment by zackkrida** [comment]
@AyanChoudhary I think you have to say 'Related to' to prevent the auto-close

**Comment by kgodey** [comment]
I didn't realize that either.

**Comment by zackkrida** [comment]
Everything in this ticket is done, so I'm going to close. We have some other open a11y issues but this one is no longer needed. Nice work everyone!
