### ISSUE TITLE
Implement assets from Design Sprint 1

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#536]
Design Sprint 1 is complete, and the final assets are available for implementation.

- [x] Implement Navbar and Footer redesigns #675 
- [x] Implement homepage middle section search form redesigns #543 
- [x] Implement image search grid redesigns #544 
- [x] Implement image details page redesigns #545

**Comment by annatuma** [comment]
@brenoferreira please add a separate ticket, linked from the list of tickets here, for the updated Collections page.
