### ISSUE TITLE
[META] Design Sprint 3: License Language Improvements

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#907]
We are making a number of changes during Design Sprint 3 on CC Search. The Design Sprint is mostly focused on License Language Improvements and attribution tool updates. Additionally, there are a few other design improvements.

- [x] License Language Improvements to Single Results Page (https://github.com/creativecommons/cccatalog-frontend/issues/889)

- [x] Homepage updates to include Collection logos (https://github.com/creativecommons/cccatalog-frontend/issues/908)

- [x] Results changes, to include filter name changes, icon addition to license filters, explanatory modals to license filters, expansion of all filter sections (i.e. no expand/collapse) which introduces dual scrolling sections.
  - [x] Expansion & scroll A/B: https://github.com/creativecommons/cccatalog-frontend/issues/909
  - [x] Minor language/placement changes: https://github.com/creativecommons/cccatalog-frontend/issues/910
  - [x] Other Filter section updates including license icons, modals, interaction between Use and License filters: https://github.com/creativecommons/cccatalog-frontend/issues/845

**Comment by zackkrida** [comment]
Last piece of this was closed by #1073
